### ISSUE TITLE
Autorollback on error ? 

### ISSUE THREAD

**Issue by sorryimfresh** [lzlabs/pg_statement_rollback#3]
Would it possible to benefit from an 'autorollback' function, so that it would not be mandatory anymore to make a call to the 'ROLLBACK TO SAVEPOINT "PgSLRAutoSvpt";' instruction ?

The goal is to get the error, but to be able to immediately go on with further request (or to rollback the entire transaction, depending on the error).

It is not clear if this function is available in pg_statement_rollback today. 

Moreover, it is not clear if pg_statement_rollback can be used in jdbc programs : the description gives a quote on jdbc, but I am not sure about this.

Thank you.

**Comment by darold** [comment]
Unfortunately PostgreSQL currently doesn't allow a full rollback at statement level feature to avoid having to execute the `ROLLBACK TO SAVEPOINT "PgSLRAutoSvpt";` instruction in case of error.

I have submitted a patch to PostgreSQL core that could allow this feature but is it still in pending status. Otherwise once this patch will be committed I have an extension ready to be released to provide full server side rollback at statement level.

So for the moment you have to issue the rollback in case of error.

About JDBC and the extension, yes it can be used just with any other programming language. Here an example of use with JDBC that should work with little editing to show you how to deal with the Java exception and the extension. 
```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;

/*
 * javac examples/rsl_example.java
 * LANG=C java -cp '/usr/share/java/postgresql-jdbc4.jar:./examples' rsl_example
 */
public class rsl_example
{

    public static void main(String[] args)
    {
        try (Connection conn = DriverManager.getConnection(
                "jdbc:postgresql://127.0.0.1:5432/contrib_regression", "gilles", "gilles"))
        {
            if (conn != null) {
                System.out.println("Connected to the database!");
            } else {
                System.out.println("Failed to make connection!");
            }
                Statement st1 = conn.createStatement();
                st1.execute("LOAD 'pg_statement_rollback'");
                st1.close();
                st1 = conn.createStatement();
                st1.execute("SET pg_statement_rollback.enabled TO on");
                st1.close();

                conn.setAutoCommit(false);
                String compiledQuery = "INSERT INTO t1 (a) VALUES (?)";
                PreparedStatement st = conn.prepareStatement(compiledQuery);
                st.setInt(1, 1);
                int records = 3;
                int[] inserted = new int[records];
                LOOP:
                for (int index = 1; index <= records; index++)
                {
                    System.out.println("insert #" + index);
                    try {
                        inserted[index-1] = st.executeUpdate();
                    } catch (SQLException e) {
                        System.out.println("ERROR: issuing automatic ROLLBACK;");
                        st1 = conn.createStatement();
                        st1.execute("ROLLBACK TO SAVEPOINT \"PgSLRAutoSvpt\"");
                        st1.close();
                        index++;
                        continue LOOP;
                    }
                }
                System.out.println("total inserted = " + inserted.length);
                st.close();
                conn.commit();
                conn.close();

        } catch (SQLException e) {
            String err = e.getSQLState();
            if (err.equals("3D000"))
            {
                System.err.format("SQL State1: %s\n%s", e.getSQLState(), e.getMessage());
            } else {
                System.err.format("SQL State2: [%s]\n%s", e.getSQLState(), e.getMessage());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by darold** [comment]
Forgot the link to the PostgreSQL patch: https://commitfest.postgresql.org/33/2860/

With this patch you will not have to deal with exception and the rollback to savepoint.

**Comment by sorryimfresh** [comment]
Hi Gilles,

Thank you for this quick answer - which is very clear and precise.
I am going to give your Java code a try. 

Thank you again and let's hope that your hook proposal will be accepted.

Anyway : thank you for this nice job on this extension, as I still can't understand why this feature is not a core function of the PostgreSQL engine.

Nicolas
